version: "3.9"
networks:
  default:
    external: true
    name: development
services:
  mongo:
    image: mongo:4
    volumes:
      - ${PWD}/data:/data/db
    ports:
      - "27017:27017"
    environment:
      - HOST=0.0.0.0
  api:
    depends_on: 
      - mongo
    build: .
    working_dir: /opt/pand-server
    ports:
      # API port
      - "3000:3000"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongo:27017
      - QUARKUS_HTTP_PORT=3000
      - HOST=0.0.0.0
    volumes:
      - /var/log/pand:/var/log/pand